version: "3.6"

networks:
  redis:
    ipam:
      config:
        - subnet: 172.79.0.0/16

services:
  redis_sentinel_1:
    image: redis:6.0.16
    container_name: redis_sentinel_1
    networks:
      redis:
        ipv4_address: 172.79.0.21
    ports:
      - 26379:23679
    volumes:
      - ~/app/redis_sentinel_1/data:/data
      - ~/app/redis_sentinel_1/conf:/conf
    command: bash -c "redis-sentinel /conf/sentinel.conf && chmod 777 /conf/sentinel.conf"
    depends_on:
      - redis_server_1
      - redis_server_2
      - redis_server_3

  redis_sentinel_2:
    image: redis:6.0.16
    container_name: redis_sentinel_2
    networks:
      redis:
        ipv4_address: 172.79.0.22
    ports:
      - 26380:23679
    volumes:
      - ~/app/redis_sentinel_2/data:/data
      - ~/app/redis_sentinel_2/conf:/conf
    command: bash -c "redis-sentinel /conf/sentinel.conf && chmod 777 /conf/sentinel.conf"
    depends_on:
      - redis_server_1
      - redis_server_2
      - redis_server_3

  redis_sentinel_3:
    image: redis:6.0.16
    container_name: redis_sentinel_3
    networks:
      redis:
        ipv4_address: 172.79.0.23
    ports:
      - 26381:23679
    volumes:
      - ~/app/redis_sentinel_3/data:/data
      - ~/app/redis_sentinel_3/conf:/conf
    command: bash -c "redis-sentinel /conf/sentinel.conf && chmod 777 /conf/sentinel.conf"
    depends_on:
      - redis_server_1
      - redis_server_2
      - redis_server_3
