version: '3'
networks:
  default:

services:
  consul_server_1:
    image: consul
    container_name: consul_server_1
    command: agent -server -bootstrap-expect=3 -node=consul_server_1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
      - default

  consul_server_2:
    image: consul
    container_name: consul_server_2
    command: agent -server -retry-join=consul_server_1 -node=consul_server_2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
      - default

  consul_server_3:
    image: consul
    container_name: consul_server_3
    command: agent -server -retry-join=consul_server_1 -node=consul_server_3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
      - default

  consul_client:
    image: consul
    container_name: consul_client
    command: agent -retry-join=consul_server_1 -node=consul_client -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
    - 8500:8500
    networks:
      - default
