version: '3.6'
services:
  amq1:
    image: webcenter/activemq
    container_name: amq1
    hostname: amq1
    #restart: always
    restart: "no"
    ports:
      - "61616:61616"
      - "8161:8161"
      - "63631:63631"
    volumes:
      - "~/app/amq1/conf/activemq.xml:/opt/activemq/conf/activemq.xml"
      - "~/app/amq1/data:/data/activemq"
      - "~/app/amq1/log:/var/log/activemq"
  amq2:
    image: webcenter/activemq
    container_name: amq2
    hostname: amq2
    restart: "no"
    ports:
      - "61617:61616"
      - "8162:8161"
      - "63632:63631"
    volumes:
      - "~/app/amq2/conf/activemq.xml:/opt/activemq/conf/activemq.xml"
      - "~/app/amq2/data:/data/activemq"
      - "~/app/amq2/log:/var/log/activemq"
  amq3:
    image: webcenter/activemq
    container_name: amq3
    hostname: amq3
    restart: "no"
    ports:
      - "61618:61616"
      - "8163:8161"
      - "63633:63631"
    volumes:
      - "~/app/amq3/conf/activemq.xml:/opt/activemq/conf/activemq.xml"
      - "~/app/amq3/data:/data/activemq"
      - "~/app/amq3/log:/var/log/activemq"
